name = "confidence-worker-api"
type = "webpack"
account_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"
workers_dev = true
route = { pattern = "kidoova.com/*", zone_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6" }
route = { pattern = "https://kidoova.com/*", zone_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6" }
compatibility_date = "2023-10-16"

[build]
command = "npm run build"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
include = ["**/*.ts"]

[[build.modules]]
type = "esModule"
name = "@tsndr/cloudflare-worker-jwt"

[site]
bucket = "./src/frontend/dist"
include = ["**/*"]
exclude = ["node_modules/**/*"]

[vars]
# Add any environment variables here
STRIPE_SECRET_KEY = "sk_live_51P8Qwj2eZvKYlo2C0JZJQZvK"
STRIPE_PRICE_ID = "price_1R55sbPEQoD1awJQfStxQA3F"
STRIPE_WEBHOOK_SECRET = "whsec_WIU3GZ6t7TdP7jH6Qmw8LvXyv3s1Jx6F"
FRONTEND_URL = "https://kidoova.com"

[[d1_databases]]
binding = "DB"
database_name = "confident-kids-playbook-db"
database_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"