name = "confidence-worker-api"
type = "webpack"
account_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"
workers_dev = true
route = { pattern = "kidoova.com/*", zone_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6" }
compatibility_date = "2023-10-16"

[build]
command = "npm run build"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
include = ["**/*.ts"]

[[build.modules]]
type = "esModule"
name = "@tsndr/cloudflare-worker-jwt"

[site]
bucket = "./src/frontend/dist"
include = ["**/*"]
exclude = ["node_modules/**/*"]

[vars]
# Add any environment variables here
STRIPE_SECRET_KEY = "sk_test_51R55ZbPEQoD1awJQDbDTRm5vQ8ng5R8FB7RVpfrh7ZOElp3PgmiAa17ZmiPOoxksDgaKxOt13DQAJxZEmRJp0wj6003MGORtGG"
STRIPE_PRICE_ID = "price_1R55sbPEQoD1awJQfStxQA3F"
STRIPE_WEBHOOK_SECRET = "whsec_bmIbEpc7URzKLoPSnf1LQtiRpA3piP3H"
FRONTEND_URL = "https://kidoova.com"

[[d1_databases]]
binding = "DB"
database_name = "confident-kids-playbook-db"
database_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"