name = "confident-kids-playbook"
main = "src/backend/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
include = ["**/*.ts"]

[[build.modules]]
type = "esModule"
name = "@tsndr/cloudflare-worker-jwt"

[vars]
# Add any environment variables here
STRIPE_SECRET_KEY = "sk_test_51R55ZbPEQoD1awJQDbDTRm5vQ8ng5R8FB7RVpfrh7ZOElp3PgmiAa17ZmiPOoxksDgaKxOt13DQAJxZEmRJp0wj6003MGORtGG"
STRIPE_PRICE_ID = "price_1R55sbPEQoD1awJQfStxQA3F"
STRIPE_WEBHOOK_SECRET = "whsec_your_stripe_webhook_secret"
FRONTEND_URL = "https://confident-kids-playbook.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "confident-kids-playbook-db"
database_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"