name = "confidence-worker-api"
type = "javascript"
main = "index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[site]
bucket = "./"

[build.upload]
format = "modules"
dir = "."
