name = "api.kidoova.com"
type = "javascript"
main = "index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "confident-kids-playbook-db"
database_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"

[vars]
FRONTEND_URL = "https://kidoova.com"
STRIPE_SECRET_KEY = "sk_test_51R55ZbPEQoD1awJQDbDTRm5vQ8ng5R8FB7RVpfrh7ZOElp3PgmiAa17ZmiPOoxksDgaKxOt13DQAJxZEmRJp0wj6003MGORtGG"
STRIPE_WEBHOOK_SECRET = "whsec_WIU3GZ6t7TdP7jH6Qmw8LvXyv3s1Jx6F"

[build]
command = "npm install"

[site]
bucket = "./"

[build.upload]
format = "modules"
dir = "."
