name = "confidence-worker-api"
main = "index.ts"
compatibility_date = "2024-12-01"

[build]
command = "npm install"

[site]
bucket = "./"

[env.production]
vars = { }

[vars]
JWT_SECRET = "ENV_JWT_SECRET"
GOOGLE_CLIENT_ID = "ENV_GOOGLE_CLIENT_ID"

[build.upload]
format = "modules"
dir = "./"
