name = "confidence-worker-api"
type = "javascript"
main = "index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "confident-kids-playbook-db"
database_id = "d0b2d163-3e3b-4193-a091-387e49b7fdb6"

[vars]
FRONTEND_URL = "https://kidoova.com"
STRIPE_SECRET_KEY = "sk_test_51R55ZbPEQoD1awJQDbDTRm5vQ8ng5R8FB7RVpfrh7ZOElp3PgmiAa17ZmiPOoxksDgaKxOt13DQAJxZEmRJp0wj6003MGORtGG"
STRIPE_WEBHOOK_SECRET = "whsec_bmIbEpc7URzKLoPSnf1LQtiRpA3piP3H"
FROM_EMAIL = "noreply@kidoova.com"
CLOUDFLARE_API_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[build]
command = "npm install"

[site]
bucket = "./"

[build.upload]
format = "modules"
dir = "."
