-- Seed theme_weeks table with data for all 52 weeks
INSERT OR REPLACE INTO theme_weeks (id, week_number, pillar_id, title, description) VALUES
  -- First Quarter (Weeks 1-13)
  ('tw_1', 1, 1, 'Self-Discovery Week', 'Explore your unique qualities and strengths'),
  ('tw_2', 2, 2, 'Growth Mindset Week', 'Learn to embrace challenges as opportunities'),
  ('tw_3', 3, 3, 'Empathy Building Week', 'Understand and connect with others'' feelings'),
  ('tw_4', 4, 4, 'Communication Skills Week', 'Express yourself clearly and confidently'),
  ('tw_5', 5, 5, 'Anxiety Management Week', 'Develop tools to handle worries and fears'),
  ('tw_6', 6, 1, 'Personal Values Week', 'Identify what matters most to you'),
  ('tw_7', 7, 2, 'Resilience Building Week', 'Bounce back from setbacks stronger'),
  ('tw_8', 8, 3, 'Social Connection Week', 'Build meaningful relationships with others'),
  ('tw_9', 9, 4, 'Leadership Skills Week', 'Learn to guide and inspire others'),
  ('tw_10', 10, 5, 'Stress Management Week', 'Handle pressure with confidence'),
  ('tw_11', 11, 1, 'Self-Expression Week', 'Share your thoughts and feelings authentically'),
  ('tw_12', 12, 2, 'Problem-Solving Week', 'Find creative solutions to challenges'),
  ('tw_13', 13, 3, 'Active Listening Week', 'Understand others through better listening'),

  -- Second Quarter (Weeks 14-26)
  ('tw_14', 14, 4, 'Teamwork Week', 'Collaborate effectively with others'),
  ('tw_15', 15, 5, 'Emotional Regulation Week', 'Manage strong emotions positively'),
  ('tw_16', 16, 1, 'Goal Setting Week', 'Plan and achieve your objectives'),
  ('tw_17', 17, 2, 'Perseverance Week', 'Keep going when things get tough'),
  ('tw_18', 18, 3, 'Kindness & Compassion Week', 'Spread positivity to others'),
  ('tw_19', 19, 4, 'Conflict Resolution Week', 'Handle disagreements constructively'),
  ('tw_20', 20, 5, 'Mindfulness Week', 'Stay present and focused'),
  ('tw_21', 21, 1, 'Identity & Values Week', 'Understand what makes you unique'),
  ('tw_22', 22, 2, 'Learning from Mistakes Week', 'Turn errors into opportunities'),
  ('tw_23', 23, 3, 'Friendship Skills Week', 'Build and maintain strong friendships'),
  ('tw_24', 24, 4, 'Public Speaking Week', 'Share your voice with confidence'),
  ('tw_25', 25, 5, 'Courage Building Week', 'Face fears with strength'),
  ('tw_26', 26, 1, 'Self-Advocacy Week', 'Stand up for your needs and beliefs'),

  -- Third Quarter (Weeks 27-39)
  ('tw_27', 27, 2, 'Innovation Week', 'Think creatively and try new things'),
  ('tw_28', 28, 3, 'Cultural Awareness Week', 'Appreciate diversity and differences'),
  ('tw_29', 29, 4, 'Assertiveness Week', 'Express needs respectfully'),
  ('tw_30', 30, 5, 'Positive Self-Talk Week', 'Build inner confidence'),
  ('tw_31', 31, 1, 'Personal Boundaries Week', 'Set healthy limits'),
  ('tw_32', 32, 2, 'Adaptability Week', 'Handle change with confidence'),
  ('tw_33', 33, 3, 'Community Connection Week', 'Build social support networks'),
  ('tw_34', 34, 4, 'Negotiation Skills Week', 'Find win-win solutions'),
  ('tw_35', 35, 5, 'Coping Strategies Week', 'Handle life''s challenges'),
  ('tw_36', 36, 1, 'Self-Care Week', 'Take care of your wellbeing'),
  ('tw_37', 37, 2, 'Growth Through Challenge Week', 'Learn from difficult situations'),
  ('tw_38', 38, 3, 'Inclusive Leadership Week', 'Lead with empathy and understanding'),
  ('tw_39', 39, 4, 'Effective Communication Week', 'Share ideas clearly and confidently'),

  -- Fourth Quarter (Weeks 40-52)
  ('tw_40', 40, 5, 'Emotional Intelligence Week', 'Understand and manage emotions'),
  ('tw_41', 41, 1, 'Personal Achievement Week', 'Celebrate your progress'),
  ('tw_42', 42, 2, 'Future Planning Week', 'Set goals for growth'),
  ('tw_43', 43, 3, 'Social Impact Week', 'Make a positive difference'),
  ('tw_44', 44, 4, 'Collaboration Skills Week', 'Work well with others'),
  ('tw_45', 45, 5, 'Resilient Mindset Week', 'Build mental strength'),
  ('tw_46', 46, 1, 'Self-Reflection Week', 'Learn from experiences'),
  ('tw_47', 47, 2, 'Problem-Solving Excellence Week', 'Master challenge-solving'),
  ('tw_48', 48, 3, 'Community Leadership Week', 'Guide and inspire others'),
  ('tw_49', 49, 4, 'Confident Communication Week', 'Express yourself boldly'),
  ('tw_50', 50, 5, 'Emotional Balance Week', 'Find peace and stability'),
  ('tw_51', 51, 1, 'Year-End Reflection Week', 'Celebrate growth and learning'),
  ('tw_52', 52, 2, 'Future Vision Week', 'Plan for continued growth'); 